version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - nginx-network

  service1:
    build: ./service1
    container_name: service1-container
    networks:
      - nginx-network

  service2:
    build: ./service2
    container_name: service2-container
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
